version: '3.9'
services:
  node:
    image: ghcr.io/foundry-rs/foundry:nightly
    ports:
      - 8545:8545
    entrypoint: ['anvil']
    command: --host=0.0.0.0 --chain-id=1337 -f=https://eth-goerli.g.alchemy.com/v2/-GlnUSi8Q2ADFXvSTgCvIHMEo8sbb0s6
    healthcheck:
      test: "wget --post-data '' --no-verbose --tries=1 --spider localhost:8545 || exit 1"
      interval: 1s
      timeout: 10s
      retries: 10

  bundler:
    image: figboy9/stackup-bundler:0.4.5-no-tracecall
    working_dir: /app
    environment:
      ERC4337_BUNDLER_ETH_CLIENT_URL: http://node:8545
      # Address: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" (10000 ETH)
      ERC4337_BUNDLER_PRIVATE_KEY: ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      ERC4337_BUNDLER_SUPPORTED_ENTRY_POINTS: 0x0576a174D229E3cFA37253523E645A78A0C91B57
    command: start --mode private
    ports:
      - 4337:4337
    depends_on:
      node:
        condition: service_healthy
